### ISSUE TITLE
Redesign login view

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs-users#4]
The login view is mostly unstyled, and not consistent with yacs-web. We should redesign the page so it looks pretty and meshes well with the main app.

**Comment by sjhuang26** [comment]
![image](https://user-images.githubusercontent.com/29558846/42006841-504709b0-7a4a-11e8-925f-65f6ade4d390.png)

**Comment by Bad-Science** [comment]
Thanks for the update @sjhuang26 !

As we discussed, please use bootstrap and just override the colors.

Also, can we put the sign up and forgot password buttons inside the container? They look a little awkward off to the side. The border is also a little thick, try using a 1px border (should be default if you use a bootstrap card component).

**Comment by sjhuang26** [comment]
![image](https://user-images.githubusercontent.com/29558846/42955721-2953c4ac-8b4c-11e8-8dfb-42576b244528.png)

It uses Bootstrap.

**Comment by Bad-Science** [comment]
Looking much better! Thanks! Can you open a PR @sjhuang
